"""
Script para neutralizar el español en archivos Markdown.
Reemplaza conjugaciones de voseo argentino y modismos regionales
por español latinoamericano neutro y formal.

Uso:
    python3 neutralize.py <archivo.md>
    python3 neutralize.py clase_1/practica_django.md

Para procesar todos los .md de una carpeta:
    for f in *.md; do python3 neutralize.py "$f"; done
"""
import sys
import re
import os


def process_file(filepath):
    if not os.path.exists(filepath):
        print(f"Archivo no encontrado: {filepath}")
        return

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    replacements = [
        # ── Verbos en presente (voseo → tuteo) ──
        (r'\btenés\b', 'tienes'),
        (r'\bpodés\b', 'puedes'),
        (r'\bquerés\b', 'quieres'),
        (r'\bsabés\b', 'sabes'),
        (r'\bhacés\b', 'haces'),
        (r'\bdecís\b', 'dices'),
        (r'\bvenís\b', 'vienes'),
        (r'\bseguís\b', 'sigues'),
        (r'\bponés\b', 'pones'),
        (r'\bcreés\b', 'crees'),
        (r'\bleés\b', 'lees'),
        (r'\bentendés\b', 'entiendes'),
        (r'\bconocés\b', 'conoces'),
        (r'\bestás\b', 'estás'),
        (r'\bobtenés\b', 'obtienes'),
        (r'\busás\b', 'usas'),
        (r'\btraés\b', 'traes'),
        (r'\belegís\b', 'eliges'),
        (r'\bveés\b', 've'),
        (r'\bdesarrollás\b', 'desarrollas'),
        (r'\baccedés\b', 'accedes'),
        (r'\bdefinís\b', 'defines'),
        (r'\bindicás\b', 'indicas'),
        (r'\blistás\b', 'listas'),
        (r'\bseleccionás\b', 'seleccionas'),
        (r'\bgenerás\b', 'generas'),
        (r'\btrabajás\b', 'trabajas'),
        (r'\bentregás\b', 'entregas'),
        (r'\bborrás\b', 'borras'),
        (r'\bpensás\b', 'piensas'),
        (r'\bvivís\b', 'vives'),
        (r'\bcorrés\b', 'corres'),
        (r'\bcopiás\b', 'copias'),
        (r'\bprobás\b', 'pruebas'),
        (r'\bguardás\b', 'guardas'),
        (r'\bcargás\b', 'cargas'),
        (r'\biniciás\b', 'inicias'),
        (r'\brecordás\b', 'recuerdas'),
        (r'\bentrás\b', 'entras'),
        (r'\blocalizás\b', 'localizas'),
        (r'\bvolvés\b', 'vuelves'),
        (r'\bdetectás\b', 'detectas'),
        (r'\bcorregís\b', 'corriges'),
        (r'\bdecidís\b', 'decides'),
        (r'\bdescribís\b', 'describes'),
        (r'\bcompletás\b', 'completas'),
        (r'\bjustificás\b', 'justificas'),
        (r'\bidentificás\b', 'identificas'),
        (r'\bcolocás\b', 'colocas'),
        (r'\bsacás\b', 'sacas'),
        (r'\barmás\b', 'armas'),
        (r'\bactualizás\b', 'actualizas'),
        (r'\bactivás\b', 'activas'),
        (r'\bdesactivás\b', 'desactivas'),
        (r'\bejecutás\b', 'ejecutas'),
        (r'\bnavegás\b', 'navegas'),
        (r'\brevisás\b', 'revisas'),
        (r'\bagregás\b', 'agregas'),
        (r'\bmodificás\b', 'modificas'),
        (r'\brenombrás\b', 'renombras'),
        (r'\bconectás\b', 'conectas'),
        (r'\bconfigurás\b', 'configuras'),
        (r'\bmandás\b', 'envías'),
        (r'\bmostrás\b', 'muestras'),
        (r'\brelacionás\b', 'relacionas'),
        (r'\basociás\b', 'asocias'),
        (r'\bjuntás\b', 'juntas'),
        (r'\beliminás\b', 'eliminas'),
        (r'\bconseguís\b', 'consigues'),
        (r'\bmirás\b', 'miras'),
        (r'\bhablás\b', 'hablas'),
        (r'\bllamás\b', 'llamas'),
        (r'\bmovés\b', 'mueves'),
        (r'\bsubís\b', 'subes'),
        (r'\bbajás\b', 'bajas'),
        (r'\bpasás\b', 'pasas'),
        (r'\bcambiás\b', 'cambias'),
        (r'\bsalís\b', 'sales'),
        (r'\baprendés\b', 'aprendes'),
        (r'\benseñás\b', 'enseñas'),
        (r'\bcompartís\b', 'compartes'),
        (r'\brecibís\b', 'recibes'),
        (r'\bsentís\b', 'sientes'),
        (r'\btocás\b', 'tocas'),
        (r'\bpulsás\b', 'pulsas'),
        (r'\bclicás\b', 'haces clic'),
        (r'\bchequeás\b', 'verificas'),
        (r'\bfiltrás\b', 'filtras'),
        (r'\bordenás\b', 'ordenas'),
        (r'\bpaginás\b', 'paginas'),
        (r'\binstanciás\b', 'instancias'),
        (r'\bheredás\b', 'heredas'),
        (r'\bextendés\b', 'extiendes'),
        (r'\bimportás\b', 'importas'),
        (r'\bexportás\b', 'exportas'),
        (r'\bdepurás\b', 'depuras'),
        (r'\btesteás\b', 'pruebas'),
        (r'\bdesplegás\b', 'desplegas'),
        (r'\bcommiteás\b', 'haces commit'),
        (r'\bpusheás\b', 'subes los cambios'),
        (r'\bpulleás\b', 'bajas los cambios'),
        (r'\bclonás\b', 'clonas'),
        (r'\bmergeás\b', 'fusionas'),
        (r'\bcorrés\b', 'corres'),
        (r'\blanzás\b', 'lanzas'),
        (r'\breiniciás\b', 'reinicias'),
        (r'\bapagás\b', 'apagas'),
        (r'\bprendés\b', 'prendes'),
        (r'\bencendés\b', 'enciendes'),
        (r'\bconvertís\b', 'conviertes'),
        (r'\btransformás\b', 'transformas'),
        (r'\bparseás\b', 'parseas'),
        (r'\bserializás\b', 'serializas'),
        (r'\bvalidás\b', 'validas'),
        (r'\bformateás\b', 'formateas'),
        (r'\bprocesás\b', 'procesas'),
        (r'\bmanejás\b', 'manejas'),
        (r'\bcontrolás\b', 'controlas'),
        (r'\bgestionás\b', 'gestionas'),
        (r'\badministrás\b', 'administras'),
        (r'\bpublicás\b', 'publicas'),
        (r'\bprotegés\b', 'proteges'),
        (r'\bexponés\b', 'expones'),
        (r'\bocultás\b', 'ocultas'),
        (r'\bdisponés\b', 'dispones'),
        (r'\bplanificás\b', 'planificas'),
        (r'\borganizás\b', 'organizas'),
        (r'\bpriorizás\b', 'priorizas'),
        (r'\bdocumentás\b', 'documentas'),
        (r'\bcomentás\b', 'comentas'),
        (r'\bregistrás\b', 'registras'),
        (r'\brespaldás\b', 'respaldas'),
        (r'\brecuperás\b', 'recuperas'),
        (r'\brestaurás\b', 'restauras'),
        (r'\bmigrás\b', 'migras'),
        (r'\bindexás\b', 'indexas'),
        (r'\binvalidás\b', 'invalidas'),
        (r'\brefrescás\b', 'refrescas'),
        (r'\bsincronizás\b', 'sincronizas'),
        (r'\bescuchás\b', 'escuchas'),
        (r'\bemitís\b', 'emites'),
        (r'\bdisparás\b', 'disparas'),
        (r'\bconsumís\b', 'consumes'),
        (r'\bsuscribís\b', 'te suscribes'),
        (r'\bobservás\b', 'observas'),
        (r'\bmonitoreas\b', 'monitoreas'),
        (r'\btrazás\b', 'trazas'),
        (r'\bdebuggeás\b', 'depuras'),
        (r'\boptimizás\b', 'optimizas'),
        (r'\brefactorizás\b', 'refactorizas'),
        (r'\breestructurás\b', 'reestructuras'),
        (r'\bmodularizás\b', 'modularizas'),
        (r'\bencapsulás\b', 'encapsulas'),
        (r'\bconstruís\b', 'construyes'),
        (r'\bdestruís\b', 'destruyes'),
        (r'\binicializás\b', 'inicializas'),
        (r'\boperás\b', 'operas'),
        (r'\bcalculás\b', 'calculas'),
        (r'\biterás\b', 'iteras'),
        (r'\brecorrés\b', 'recorres'),
        (r'\bencontrás\b', 'encuentras'),
        (r'\bcomparás\b', 'comparas'),
        (r'\bclasificás\b', 'clasificas'),
        (r'\bagrupás\b', 'agrupas'),
        (r'\bseparás\b', 'separas'),
        (r'\bdividís\b', 'divides'),
        (r'\bcombinás\b', 'combinas'),
        (r'\bunís\b', 'unes'),
        (r'\bmapeás\b', 'mapeas'),
        (r'\breducís\b', 'reduces'),
        (r'\baplicás\b', 'aplicas'),
        (r'\binvocás\b', 'invocas'),
        (r'\bretornás\b', 'retornas'),
        (r'\bdevolvés\b', 'devuelves'),
        (r'\barrojás\b', 'arrojas'),
        (r'\bcapturás\b', 'capturas'),
        (r'\bpropagás\b', 'propagas'),
        (r'\bregenerás\b', 'regeneras'),
        (r'\brepetís\b', 'repites'),
        (r'\bcontinuás\b', 'continúas'),
        (r'\bsaltás\b', 'saltas'),
        (r'\bregresás\b', 'regresas'),
        (r'\bvás\b', 'vas'),
        (r'\badaptás\b', 'adaptas'),
        (r'\bsobrescribís\b', 'sobreescribes'),
        (r'\binyectás\b', 'inyectas'),
        (r'\bdependés\b', 'dependes'),
        (r'\bimplementás\b', 'implementas'),
        (r'\bintegrás\b', 'integras'),
        (r'\bdesconectás\b', 'desconectas'),
        (r'\bautenticás\b', 'autenticas'),
        (r'\bautorizás\b', 'autorizas'),
        (r'\bdenegás\b', 'denegas'),
        (r'\brechazás\b', 'rechazas'),
        (r'\baceptás\b', 'aceptas'),
        (r'\baprobás\b', 'apruebas'),
        (r'\bconfirmás\b', 'confirmas'),
        (r'\bencriptás\b', 'encriptas'),
        (r'\bdesencriptás\b', 'desencriptas'),
        (r'\bhashéas\b', 'hasheas'),
        (r'\bfirmás\b', 'firmas'),
        (r'\bauditás\b', 'auditas'),
        (r'\bnotificás\b', 'notificas'),
        (r'\brespondés\b', 'respondes'),
        (r'\bservís\b', 'sirves'),
        (r'\bhosteás\b', 'alojas'),
        (r'\btransferís\b', 'transfières'),
        (r'\breemplazás\b', 'reemplazas'),
        (r'\barchivás\b', 'archivas'),
        (r'\bcomprimís\b', 'comprimes'),
        (r'\bdescomprimís\b', 'descomprimes'),
        (r'\bcompilás\b', 'compilas'),
        (r'\buildás\b', 'construyes'),
        (r'\bandás\b', 'vas'),
        (r'\bquedás\b', 'quedas'),
        (r'\bempezás\b', 'empiezas'),
        (r'\bterminás\b', 'terminas'),
        (r'\bfinalizás\b', 'finalizas'),
        (r'\banuás\b', 'anulas'),
        (r'\bcancelás\b', 'cancelas'),
        (r'\bcerrás\b', 'cierras'),
        (r'\bdescartás\b', 'descartas'),
        (r'\bresolvés\b', 'resuelves'),
        (r'\bfallás\b', 'fallas'),
        (r'\bequivocás\b', 'te equivocas'),
        (r'\bupdatás\b', 'actualizas'),
        (r'\bdeprecás\b', 'deprecas'),
        (r'\balterás\b', 'alteras'),
        (r'\btruncás\b', 'truncas'),
        (r'\bpurgás\b', 'purgas'),
        (r'\blimipiás\b', 'limpias'),
        (r'\blimpiás\b', 'limpias'),
        (r'\bescapeás\b', 'escapas'),
        (r'\brenderizás\b', 'renderizas'),
        (r'\bdiseñás\b', 'diseñas'),
        (r'\banimás\b', 'animas'),
        (r'\bpreguntás\b', 'preguntas'),
        (r'\bcontestás\b', 'contestas'),
        (r'\bsumás\b', 'sumas'),
        (r'\brestás\b', 'restas'),
        (r'\bmultiplicás\b', 'multiplicas'),
        (r'\bcomprobás\b', 'compruebas'),
        (r'\bdecostrás\b', 'destruyes'),
        (r'\binsertar\b', 'insertar'),
        (r'\bpostulás\b', 'postulas'),
        (r'\bcrecés\b', 'creces'),
        (r'\bayudás\b', 'ayuda'),

        # ── Imperativos (voseo → tuteo) ──

        (r'\babrís\b', 'abres'),
        (r'\bhacé\b', 'haz'),
        (r'\bponé\b', 'pon'),
        (r'\bdecí\b', 'di'),
        (r'\bvení\b', 'ven'),
        (r'\bseguí\b', 'sigue'),
        (r'\bmirá\b', 'mira'),
        (r'\bfijate\b', 'fíjate'),
        (r'\bacordate\b', 'acuérdate'),
        (r'\bolvidate\b', 'olvídate'),
        (r'\basegurate\b', 'asegúrate'),
        (r'\banotá\b', 'anota'),
        (r'\bbuscá\b', 'busca'),
        (r'\bcreá\b', 'crea'),
        (r'\babrí\b', 'abre'),
        (r'\bejecutá\b', 'ejecuta'),
        (r'\bnavegá\b', 'navega'),
        (r'\bprobá\b', 'prueba'),
        (r'\bcorré\b', 'corre'),
        (r'\brevisá\b', 'revisa'),
        (r'\bagregá\b', 'agrega'),
        (r'\bmodificá\b', 'modifica'),
        (r'\brenombrá\b', 'renombra'),
        (r'\bactualizá\b', 'actualiza'),
        (r'\bescribí\b', 'escribe'),
        (r'\bguardá\b', 'guarda'),
        (r'\bcargá\b', 'carga'),
        (r'\biniciá\b', 'inicia'),
        (r'\bverificá\b', 'verifica'),
        (r'\binstalá\b', 'instala'),
        (r'\brecordá\b', 'recuerda'),
        (r'\bentrá\b', 'entra'),
        (r'\bdejalo\b', 'déjalo'),
        (r'\bdescargalo\b', 'descárgalo'),
        (r'\blocalizá\b', 'localiza'),
        (r'\bvolvé\b', 'vuelve'),
        (r'\bbajá\b', 'baja'),
        (r'\btipear\b', 'escribir'),
        (r'\btipeando\b', 'escribiendo'),
        (r'\brepetila\b', 'repítela'),
        (r'\bdetectá\b', 'detecta'),
        (r'\bcorregí\b', 'corrige'),
        (r'\bdecidí\b', 'decide'),
        (r'\bdescribí\b', 'describe'),
        (r'\belegí\b', 'elige'),
        (r'\bcompletá\b', 'completa'),
        (r'\bjustificá\b', 'justifica'),
        (r'\bdefiní\b', 'define'),
        (r'\bindentificá\b', 'identifica'),
        (r'\bidentificá\b', 'identifica'),
        (r'\blistá\b', 'lista'),
        (r'\bcolocá\b', 'coloca'),
        (r'\bsacá\b', 'saca'),
        (r'\barmá\b', 'arma'),
        (r'\bcopiá\b', 'copia'),
        (r'\bgenerá\b', 'genera'),
        (r'\bindicá\b', 'indica'),
        (r'\bseleccioná\b', 'selecciona'),
        (r'\baccedé\b', 'accede'),
        (r'\bactivá\b', 'activa'),
        (r'\bdesactivá\b', 'desactiva'),
        (r'\beliminá\b', 'elimina'),
        (r'\bborrá\b', 'borra'),
        (r'\bconseguí\b', 'consigue'),
        (r'\bmostrá\b', 'muestra'),
        (r'\btraé\b', 'trae'),
        (r'\bllévá\b', 'lleva'),
        (r'\bjuntá\b', 'junta'),
        (r'\basociá\b', 'asocia'),
        (r'\brelacioná\b', 'relaciona'),
        (r'\bconectá\b', 'conecta'),
        (r'\bconfigurá\b', 'configura'),
        (r'\bapagá\b', 'apaga'),
        (r'\bmandá\b', 'envía'),
        (r'\bobtenés\b', 'obtienes'),
        (r'\brevertí\b', 'reviertes'),
        (r'\bcontá\b', 'cuenta'),

        # ── Mayúsculas ──
        (r'\bDefinís\b', 'Defines'),
        (r'\bTenés\b', 'Tienes'),
        (r'\bPodés\b', 'Puedes'),
        (r'\bQuerés\b', 'Quieres'),
        (r'\bSabés\b', 'Sabes'),
        (r'\bHacés\b', 'Haces'),
        (r'\bHacé\b', 'Haz'),
        (r'\bPoné\b', 'Pon'),
        (r'\bMirá\b', 'Mira'),
        (r'\bFijate\b', 'Fíjate'),
        (r'\bAsegurate\b', 'Asegúrate'),
        (r'\bAnotá\b', 'Anota'),
        (r'\bBuscá\b', 'Busca'),
        (r'\bCreá\b', 'Crea'),
        (r'\bAbrí\b', 'Abre'),
        (r'\bEjecutá\b', 'Ejecuta'),
        (r'\bNavegá\b', 'Navega'),
        (r'\bProbá\b', 'Prueba'),
        (r'\bCorré\b', 'Corre'),
        (r'\bRevisá\b', 'Revisa'),
        (r'\bAgregá\b', 'Agrega'),
        (r'\bModificá\b', 'Modifica'),
        (r'\bRenombrá\b', 'Renombra'),
        (r'\bActualizá\b', 'Actualiza'),
        (r'\bEscribí\b', 'Escribe'),
        (r'\bGuardá\b', 'Guarda'),
        (r'\bCargá\b', 'Carga'),
        (r'\bIniciá\b', 'Inicia'),
        (r'\bVerificá\b', 'Verifica'),
        (r'\bInstalá\b', 'Instala'),
        (r'\bRecordá\b', 'Recuerda'),
        (r'\bEntrá\b', 'Entra'),
        (r'\bLocalizá\b', 'Localiza'),
        (r'\bVolvé\b', 'Vuelve'),
        (r'\bDetectá\b', 'Detecta'),
        (r'\bCorregí\b', 'Corrige'),
        (r'\bDecidí\b', 'Decide'),
        (r'\bElegí\b', 'Elige'),
        (r'\bCompletá\b', 'Completa'),
        (r'\bJustificá\b', 'Justifica'),
        (r'\bDefiní\b', 'Define'),
        (r'\bIdentificá\b', 'Identifica'),
        (r'\bListá\b', 'Lista'),
        (r'\bColocá\b', 'Coloca'),
        (r'\bSacá\b', 'Saca'),
        (r'\bArmá\b', 'Arma'),
        (r'\bCopiá\b', 'Copia'),
        (r'\bGenerá\b', 'Genera'),
        (r'\bIndicá\b', 'Indica'),
        (r'\bSeleccioná\b', 'Selecciona'),
        (r'\bAccedé\b', 'Accede'),
        (r'\bActivá\b', 'Activa'),
        (r'\bDesactivá\b', 'Desactiva'),
        (r'\bEliminá\b', 'Elimina'),
        (r'\bBorrá\b', 'Borra'),
        (r'\bConseguí\b', 'Consigue'),
        (r'\bMostrá\b', 'Muestra'),
        (r'\bTraé\b', 'Trae'),
        (r'\bJuntá\b', 'Junta'),
        (r'\bAsociá\b', 'Asocia'),
        (r'\bRelacioná\b', 'Relaciona'),
        (r'\bConectá\b', 'Conecta'),
        (r'\bConfigurá\b', 'Configura'),
        (r'\bApagá\b', 'Apaga'),
        (r'\bMandá\b', 'Envía'),
        (r'\bObtenés\b', 'Obtienes'),
        (r'\bUsás\b', 'Usas'),
        (r'\bTraés\b', 'Traes'),
        (r'\bElegís\b', 'Eliges'),
        (r'\bDesarrollás\b', 'Desarrollas'),
        (r'\bAccedés\b', 'Accedes'),
        (r'\bTrabajás\b', 'Trabajas'),
        (r'\bEntregás\b', 'Entregas'),
        (r'\bBorrás\b', 'Borras'),
        (r'\bPensás\b', 'Piensas'),
        (r'\bVivís\b', 'Vives'),
        (r'\bCorrés\b', 'Corres'),
        (r'\bCopiás\b', 'Copias'),
        (r'\bProbás\b', 'Pruebas'),
        (r'\bGuardás\b', 'Guardas'),
        (r'\bCargás\b', 'Cargas'),
        (r'\bIniciás\b', 'Inicias'),
        (r'\bRecordás\b', 'Recuerdas'),
        (r'\bEntrás\b', 'Entras'),
        (r'\bLocalizás\b', 'Localizas'),
        (r'\bVolvés\b', 'Vuelves'),
        (r'\bDetectás\b', 'Detectas'),
        (r'\bCompletás\b', 'Completas'),
        (r'\bAplicás\b', 'Aplicas'),
        (r'\bImplementás\b', 'Implementas'),
        (r'\bOptimizás\b', 'Optimizas'),
        (r'\bValidás\b', 'Validas'),
        (r'\bFiltrás\b', 'Filtras'),
        (r'\bOrdenás\b', 'Ordenas'),
        (r'\bMostrás\b', 'Muestras'),
        (r'\bRegistrás\b', 'Registras'),
        (r'\bPublicás\b', 'Publicas'),
        (r'\bProtegés\b', 'Proteges'),
        (r'\bConvertís\b', 'Conviertes'),
        (r'\bProcesás\b', 'Procesas'),
        (r'\bDocumentás\b', 'Documentas'),
        (r'\bOrganizás\b', 'Organizas'),
        (r'\bPlanificás\b', 'Planificas'),
        (r'\bGestionás\b', 'Gestionas'),
        (r'\bSincronizás\b', 'Sincronizas'),
        (r'\bMonitoreás\b', 'Monitoreas'),
        (r'\bDepurás\b', 'Depuras'),
        (r'\bRefactorizás\b', 'Refactorizas'),
        (r'\bMigrás\b', 'Migras'),
        (r'\bDesplegás\b', 'Desplegas'),
        (r'\bSubís\b', 'Subes'),
        (r'\bBajás\b', 'Bajas'),
        (r'\bAndás\b', 'Vas'),
        (r'\bEmpezás\b', 'Empiezas'),
        (r'\bTerminás\b', 'Terminas'),
        (r'\bCancelás\b', 'Cancelas'),
        (r'\bResolvés\b', 'Resuelves'),
        (r'\bCorregís\b', 'Corriges'),
        (r'\bComprobás\b', 'Compruebas'),
        (r'\bEncriptás\b', 'Encriptas'),
        (r'\bAutenticás\b', 'Autenticas'),
        (r'\bAutorizás\b', 'Autorizas'),
        (r'\bRechazás\b', 'Rechazas'),
        (r'\bAceptás\b', 'Aceptas'),
        (r'\bAprobás\b', 'Apruebas'),
        (r'\bConfirmás\b', 'Confirmas'),
        (r'\bNotificás\b', 'Notificas'),
        (r'\bRespondés\b', 'Respondes'),
        (r'\bServís\b', 'Sirves'),
        (r'\bReemplazás\b', 'Reemplazas'),
        (r'\bArchivás\b', 'Archivas'),
        (r'\bCompilás\b', 'Compilas'),
        (r'\bEmpezás\b', 'Empiezas'),
        (r'\bFinalizás\b', 'Finalizas'),
        (r'\bCerrás\b', 'Cierras'),
        (r'\bDescartás\b', 'Descartas'),
        (r'\bFallás\b', 'Fallas'),
        (r'\bAlterás\b', 'Alteras'),
        (r'\bTruncás\b', 'Truncas'),
        (r'\bPurgás\b', 'Purgas'),
        (r'\bLimpiás\b', 'Limpias'),
        (r'\bRenderizás\b', 'Renderizas'),
        (r'\bDiseñás\b', 'Diseñas'),
        (r'\bAnimás\b', 'Animas'),
        (r'\bPreguntás\b', 'Preguntas'),
        (r'\bContestás\b', 'Contestas'),
        (r'\bSumás\b', 'Sumas'),
        (r'\bRestás\b', 'Restas'),
        (r'\bPostulás\b', 'Postulas'),
        (r'\bCrecés\b', 'Creces'),
        (r'\bRevertí\b', 'Reviertes'),
        (r'\bRevertís\b', 'Reviertes'),
        (r'\brevertís\b', 'reviertes'),
        (r'\bAyudás\b', 'Ayuda'),
        (r'\bContá\b', 'Cuenta'),

        # ── Modismos, regionalismos y expresiones coloquiales ──
        (r'\bsos\b', 'eres'),
        (r'\bSos\b', 'Eres'),
        (r'\bacá\b', 'aquí'),
        (r'\bAcá\b', 'Aquí'),
        (r'\bACÁ\b', 'AQUÍ'),
        (r'\bVos\b', 'Tú'),
        (r'\bvos\b', 'tú'),
        (r'\bA ver\b', 'Veamos'),
        (r'\ba ver\b', 'veamos'),
        (r'\btipear\b', 'escribir'),
        (r'\btipeando\b', 'escribiendo'),
        (r'\btypeando\b', 'escribiendo'),
        (r'\bcon tú\b', 'contigo'),
        (r'\bcon tú\b', 'contigo'),
        (r'\bcontactame\b', 'contáctame'),
        (r'\bcomentame\b', 'coméntame'),
        (r'\bayudame\b', 'ayúdame'),
        (r'\benvianos\b', 'envíanos'),
        (r'\bmandanos\b', 'envíanos'),
        (r'\benviame\b', 'envíame'),
        (r'\bmandame\b', 'envíame'),
        (r'\bmandálo\b', 'envíalo'),
        (r'\bmandalo\b', 'envíalo'),
        (r'\bcontame\b', 'cuéntame'),
        (r'\bcomunicate\b', 'comunícate'),
    ]

    new_content = content
    changes = 0
    for pattern, replacement in replacements:
        new_content, count = re.subn(pattern, replacement, new_content)
        changes += count

    if changes > 0:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"✅ Modificado ({changes} cambios): {filepath}")
    else:
        print(f"✔️  Sin cambios: {filepath}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Uso: python3 neutralize.py <archivo.md>")
        print("     python3 neutralize.py archivo1.md archivo2.md ...")
        sys.exit(1)

    for filepath in sys.argv[1:]:
        process_file(filepath)
