# Generated by Django 6.0.3 on 2026-03-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('types', models.JSONField(default=list)),
                ('hp', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('special_attack', models.IntegerField(default=0)),
                ('special_defense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('total_power', models.IntegerField(default=0)),
                ('location', models.CharField(choices=[('party', 'Party'), ('pc', 'PC Box')], default='party', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'captured_at'],
            },
        ),
    ]
